### ISSUE TITLE
mse 0.30 rather mse 0.06 in paper

### ISSUE THREAD

**Issue by zblan** [ARiSE-Lab/deepTest#1]
I use the rambo model(rambo_reproduce.py) to test the CH2_final dataset, I test by your description in readme.md. Download the model weight and train_mean file in [https://github.com/udacity/self-driving-car/tree/master/steering-models/evaluation](url) But i get mse 0.30 rather 0.06. Do you have some thoughts about this problem?

**Comment by yuchi1989** [comment]
Hi @zblan , for rambo model, which backend are you using for Keras? The backend should be theano instead of tensorflow.
