### ISSUE TITLE
Cannot find HMB3.bag file

### ISSUE THREAD

**Issue by Darylnn** [ARiSE-Lab/deepTest#2]
I tried running this command
`python generate_hmb3.py --bagfile HMB_3.bag`

but there was no HMB3.bag file so I tried to retrieve it from the link provided in the README (https://github.com/udacity/self-driving-car/blob/master/datasets/CH2/HMB_3.bag.tar.gz.torrent) but I only downloaded a torrent file. I tried using a bitTorrent client to unpack it but it does not seem to be seeding.

I would be really appreciate your help if you could point me in the right direction of getting this HMB_3.bag file so that I could carry out the DeepTest algorithm. Thank you for also providing this source code for the community to learn.

**Comment by yuchi1989** [comment]
Hi @Wrathar , this dataset is maintained by "The Udacity open source self-driving car project". You can try to contact them about the dataset? Here is the repository link. https://github.com/udacity/self-driving-car
dataset link: https://github.com/udacity/self-driving-car/tree/master/datasets/CH2

**Comment by nosherwanijaz** [comment]
Hello @yuchi1989. I read DeepTest paper and tried to replicate your work. I was able to run most of the project. However, I had some questions:
1. After generating images and csv file using the guided python script, how did you calculate mean squared error for the images generated. I didn't find any code in the repository for that. Can you guide on that?
2. How did you guys drew arrows on the images? Are they drawn with the real steering angle specified in the csv file? If yes, then what tool did you guys use to draw those arrows?

**Comment by yuchi1989** [comment]
Hi @nosherwanijaz 

> Hello @yuchi1989. I read DeepTest paper and tried to replicate your work. I was able to run most of the project. However, I had some questions:
> 
> 1. After generating images and csv file using the guided python script, how did you calculate mean squared error for the images generated. I didn't find any code in the repository for that. Can you guide on that?

See this section for mean square error
https://github.com/ARiSE-Lab/deepTest/blob/5d83a0e0b6997c584c8b6f0ab9e1e802c39801c9/models/epoch_reproduce.py#L46-L59


> 2. How did you guys drew arrows on the images? Are they drawn with the real steering angle specified in the csv file? If yes, then what tool did you guys use to draw those arrows?

We were using Python opencv library to draw arrows.

**Comment by nosherwanijaz** [comment]
@yuchi1989 

Do you have any code for drawing arrows using opencv?

**Comment by yuchi1989** [comment]
Hi I shared the hmb3.bag file here because the original published torrent file(https://github.com/udacity/self-driving-car/blob/master/datasets/CH2/HMB_3.bag.tar.gz.torrent) is not seeding any more. This file may help a lot of people for research purpose. If you use this link you need to adhere to any restriction from the original site(https://github.com/udacity/self-driving-car). Also I don't use it for profit.

https://drive.google.com/file/d/1Cna33hR2aEfS4BGiaUtmyWkiqu9BTce_/view?usp=sharing
