### ISSUE TITLE
HMB_3 test data

### ISSUE THREAD

**Issue by trqminh** [ARiSE-Lab/deepTest#4]
Hi @yuchi1989,
I follow the readme to prepare the datasets. However, I cannot download the HMB_3 experiment since there is no seed for the torrent link (https://github.com/udacity/self-driving-car/blob/master/datasets/CH2/HMB_3.bag.tar.gz.torrent).

Do you know any other ways to access the data? Thank you for your consideration.

**Comment by MrVanGoghYang** [comment]
I have the same problem too.I think the link on that website has expired.
Anyone could get HMB_3.bag dataset?Thx for any help.

**Comment by Yingxiu-Chang** [comment]
I have the same problem. There is no seed for the HMB_3 torrent. 
Thx for help if any tells another way?

**Comment by shigri007** [comment]
anyone pls share the link to download the test data
